FROM openmodelica/openmodelica:v1.9.5-minimal

MAINTAINER Martin Sjölund <martin.sjolund@liu.se>

RUN apt-get update && apt-get install -qy openmodelica \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
