FROM openmodelica/openmodelica:v1.14.2-minimal

MAINTAINER Martin Sjölund <martin.sjolund@liu.se>

RUN apt-get update && apt-get install -qy python3-pip \
    && pip3 install --no-cache-dir ompython \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
