FROM openmodelica/openmodelica:v1.16.2-ompython

MAINTAINER Martin Sjölund <martin.sjolund@liu.se>

RUN apt-get update && apt-get install -qy openmodelica libomccpp \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
