ARG BASE

FROM ${BASE}

LABEL MAINTAINER Martin Sjölund <martin.sjolund@liu.se>

RUN export DEBIAN_FRONTEND="noninteractive" && apt-get update && apt-get install --no-install-recommends -qy python3-pip python3-psutil python3-zmq python3-numpy \
    && pip3 install --no-cache-dir --only-binary psutil,pyzmq,numpy "ompython>=3.4.0" \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
