FROM openmodelica/openmodelica:1.14.1

MAINTAINER Martin Sjölund <martin.sjolund@liu.se>

RUN apt-get update && apt-get install -qy openmodelica \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
